# Generated by Django 5.1.7 on 2025-04-29 23:50

import django.db.models.deletion
import django.utils.timezone
import produto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalheTecnicoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('icone_bootstrap', models.CharField(blank=True, max_length=100, null=True)),
                ('detalhe_tecnico', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'detalhe_tecnico_valor',
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalheTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('icone_bootstrap', models.CharField(blank=True, max_length=100, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalhes_tecnicos', to='produto.categoriaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.now)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='novo', max_length=20)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('descartado', 'Descartado')], default='ativo', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto/imagens/', validators=[produto.models.validate_image, produto.models.validate_image_size])),
                ('estoque_atual', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.categoriaproduto')),
                ('fichatecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichatecnicas', to='produto.detalhetecnicovalor')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.localizacaoproduto')),
            ],
            options={
                'permissions': [('pode_adicionar_ativo', 'Pode adicionar ativo'), ('pode_modificar_ativo', 'Pode modificar ativo'), ('pode_deletar_ativo', 'Pode deletar ativo'), ('pode_visualizar_ativo', 'Pode visualizar ativo')],
            },
        ),
        migrations.AddField(
            model_name='detalhetecnicovalor',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalhes_categoria', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='detalhetecnicovalor',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe_tecnico', to='produto.produto'),
        ),
    ]
