# Generated by Django 5.2 on 2025-05-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhetecnicovalor',
            name='detalhe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores', to='produto.detalhetecnico'),
        ),
    ]
