# Generated by Django 5.2 on 2025-05-18 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_aquisicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
