# Generated by Django 5.2 on 2025-05-18 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_detalhetecnicovalor_detalhe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhetecnicovalor',
            name='detalhe',
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_aquisicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
