# Generated by Django 5.2 on 2025-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='consultas_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
