# Generated by Django 5.2 on 2025-05-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_historico_consultas_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='consultas_json',
        ),
    ]
