# Generated by Django 5.2 on 2025-05-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_remove_historico_consultas_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='tipo_alteracao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('SEARCH', 'Consulta')], max_length=50),
        ),
    ]
