# Generated by Django 5.2 on 2025-05-12 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0002_alter_produto_localizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('imei', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numero_serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status_atual', models.CharField(blank=True, choices=[('ativo', 'Disponível'), ('em_uso', 'Alocado'), ('manutencao', 'Em Manutenção'), ('baixado', 'Baixado')], max_length=20, null=True)),
                ('status_ativo', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cadastro')),
                ('tipo_entrada', models.CharField(blank=True, choices=[('entrada', 'Entrada de Ativo')], default='entrada', max_length=20, null=True)),
                ('usuario_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.categoriaproduto')),
                ('codigo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos_por_codigo', to='produto.produto')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.localizacaoproduto')),
                ('localizacao_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_atual', to='produto.localizacaoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cadastro')),
                ('status_anterior', models.CharField(choices=[('ativo', 'Disponível'), ('em_uso', 'Alocado'), ('manutencao', 'Em Manutenção'), ('baixado', 'Baixado')], max_length=20)),
                ('status_novo', models.CharField(choices=[('ativo', 'Disponível'), ('em_uso', 'Alocado'), ('manutencao', 'Em Manutenção'), ('baixado', 'Baixado')], max_length=20)),
                ('usuario_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_final', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimento.ativo')),
                ('local_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='produto.localizacaoproduto')),
                ('local_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='produto.localizacaoproduto')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
