# Generated by Django 5.2 on 2025-05-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativo',
            old_name='localizacao_atual',
            new_name='localizacao_atual_id',
        ),
    ]
