# Generated by Django 5.2 on 2025-05-12 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0002_rename_localizacao_atual_ativo_localizacao_atual_id'),
        ('produto', '0002_alter_produto_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='localizacao_atual_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_atual', to='produto.localizacaoproduto'),
        ),
    ]
