# Generated by Django 5.2 on 2025-05-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0003_alter_ativo_localizacao_atual_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativo',
            old_name='localizacao_atual_id',
            new_name='localizacao_atual',
        ),
    ]
